name: Build Docker Image

on:
  push:
    branches: [main]
    paths: ['docs/Dockerfile']
  pull_request:
    branches: [main]
    paths: ['docs/Dockerfile']

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest service image
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: dowhy-examples-notebooks-deps
          docker-image-tag: latest # optional
          dockerfile-path: ./docs/Dockerfile # optional
